local Ranked = require('lib.ranked_logic')

describe('expectedScore', function()
    it('returns 0.5 for equal ratings', function()
        expect(Ranked.expectedScore(1000, 1000)).toBeCloseTo(0.5, 0.001)
    end)

    it('returns higher score for stronger player', function()
        local score = Ranked.expectedScore(1400, 1000)
        expect(score).toBeGreaterThan(0.5)
    end)

    it('returns lower score for weaker player', function()
        local score = Ranked.expectedScore(1000, 1400)
        expect(score).toBeLessThan(0.5)
    end)

    it('complements sum to 1.0', function()
        local a = Ranked.expectedScore(1200, 800)
        local b = Ranked.expectedScore(800, 1200)
        expect(a + b).toBeCloseTo(1.0, 0.001)
    end)

    it('returns ~0.76 for 200 point advantage', function()
        local score = Ranked.expectedScore(1200, 1000)
        expect(score).toBeCloseTo(0.76, 0.01)
    end)
end)

describe('calculateMMRChange', function()
    it('gives equal gain/loss for equal MMR', function()
        local gain, loss = Ranked.calculateMMRChange(1000, 1000)
        expect(gain).toBe(16)
        expect(loss).toBe(-16)
    end)

    it('gives less gain for beating a weaker opponent', function()
        local gain, _ = Ranked.calculateMMRChange(1500, 1000)
        local gainEqual, _ = Ranked.calculateMMRChange(1000, 1000)
        expect(gain).toBeLessThan(gainEqual)
    end)

    it('gives more gain for beating a stronger opponent', function()
        local gain, _ = Ranked.calculateMMRChange(1000, 1500)
        local gainEqual, _ = Ranked.calculateMMRChange(1000, 1000)
        expect(gain).toBeGreaterThan(gainEqual)
    end)

    it('enforces minimum gain of 5', function()
        local gain, _ = Ranked.calculateMMRChange(2500, 500)
        expect(gain).toBeGreaterThanOrEqual(5)
    end)

    it('enforces minimum loss of -5', function()
        local _, loss = Ranked.calculateMMRChange(500, 2500)
        expect(loss).toBeLessThanOrEqual(-5)
    end)

    it('respects custom K-factor', function()
        local gain64, _ = Ranked.calculateMMRChange(1000, 1000, 64)
        local gain16, _ = Ranked.calculateMMRChange(1000, 1000, 16)
        expect(gain64).toBeGreaterThan(gain16)
    end)
end)

describe('getTierForMMR', function()
    it('returns bronze for MMR 0', function()
        expect(Ranked.getTierForMMR(0)).toBe('bronze')
    end)

    it('returns bronze for MMR 499', function()
        expect(Ranked.getTierForMMR(499)).toBe('bronze')
    end)

    it('returns silver for MMR 500', function()
        expect(Ranked.getTierForMMR(500)).toBe('silver')
    end)

    it('returns gold for MMR 1000', function()
        expect(Ranked.getTierForMMR(1000)).toBe('gold')
    end)

    it('returns platinum for MMR 1500', function()
        expect(Ranked.getTierForMMR(1500)).toBe('platinum')
    end)

    it('returns diamond for MMR 2000', function()
        expect(Ranked.getTierForMMR(2000)).toBe('diamond')
    end)

    it('returns blacklist for MMR 2500', function()
        expect(Ranked.getTierForMMR(2500)).toBe('blacklist')
    end)

    it('returns blacklist for very high MMR', function()
        expect(Ranked.getTierForMMR(5000)).toBe('blacklist')
    end)

    it('returns bronze for negative MMR', function()
        expect(Ranked.getTierForMMR(-100)).toBe('bronze')
    end)
end)

describe('applyMatchResult', function()
    it('promotes winner across tier boundary', function()
        local result = Ranked.applyMatchResult(490, 1000)
        expect(result.newWinnerTier).toBe('silver')
        expect(result.winnerPromoted).toBeTrue()
    end)

    it('does not demote loser below tier floor', function()
        local result = Ranked.applyMatchResult(1000, 500, 'silver')
        expect(result.newLoserMMR).toBeGreaterThanOrEqual(500)
    end)

    it('never drops MMR below 0', function()
        local result = Ranked.applyMatchResult(500, 10)
        expect(result.newLoserMMR).toBeGreaterThanOrEqual(0)
    end)

    it('returns correct structure', function()
        local result = Ranked.applyMatchResult(1000, 1000)
        expect(result.winnerGain).toNotBeNil()
        expect(result.loserLoss).toNotBeNil()
        expect(result.newWinnerMMR).toNotBeNil()
        expect(result.newLoserMMR).toNotBeNil()
        expect(result.newWinnerTier).toNotBeNil()
        expect(result.newLoserTier).toNotBeNil()
    end)

    it('winner MMR increases and loser MMR decreases', function()
        local result = Ranked.applyMatchResult(1000, 1000)
        expect(result.newWinnerMMR).toBeGreaterThan(1000)
        expect(result.newLoserMMR).toBeLessThan(1000)
    end)
end)
