fx_version 'cerulean'
game 'gta5'

author 'BlackList Racing'
description 'Vehicle handling overrides - edit .meta files and /refresh handling'
version '1.0.0'

server_script 'server.lua'
client_script 'client.lua'

files {
    'bronze/*.meta',
    'silver/*.meta',
    'gold/*.meta',
    'platinum/*.meta',
    'diamond/*.meta',
    'blacklist/*.meta',
    'custom/*.meta',
}

-- Bronze tier (105 mph)
data_file 'HANDLING_FILE' 'bronze/gb_cometcl.meta'
data_file 'HANDLING_FILE' 'bronze/rh4.meta'
data_file 'HANDLING_FILE' 'bronze/ballerc.meta'
data_file 'HANDLING_FILE' 'bronze/futo.meta'

-- Silver tier (115 mph)
data_file 'HANDLING_FILE' 'silver/gb_cometclf.meta'
data_file 'HANDLING_FILE' 'silver/gb_retinueloz.meta'
data_file 'HANDLING_FILE' 'silver/gb_schrauber.meta'

-- Gold tier (125 mph)
data_file 'HANDLING_FILE' 'gold/roxanne.meta'
data_file 'HANDLING_FILE' 'gold/buffaloh.meta'
data_file 'HANDLING_FILE' 'gold/jester5.meta'
data_file 'HANDLING_FILE' 'gold/sent6.meta'
data_file 'HANDLING_FILE' 'gold/gb_gresleystx.meta'

-- Platinum tier (135 mph)
data_file 'HANDLING_FILE' 'platinum/gb_argento7f.meta'
data_file 'HANDLING_FILE' 'platinum/gb_solace.meta'
data_file 'HANDLING_FILE' 'platinum/gb_sultanrsx.meta'

-- Diamond tier (145 mph)
data_file 'HANDLING_FILE' 'diamond/gb_tr3s.meta'

-- BlackList tier (155 mph)
data_file 'HANDLING_FILE' 'blacklist/gsttoros1.meta'
data_file 'HANDLING_FILE' 'blacklist/gb_comets2r.meta'

-- Custom (PixaCars)
data_file 'HANDLING_FILE' 'custom/as_nexus.meta'
data_file 'HANDLING_FILE' 'custom/as_zr350.meta'
data_file 'HANDLING_FILE' 'custom/asteropers.meta'
data_file 'HANDLING_FILE' 'custom/benefacgt.meta'
data_file 'HANDLING_FILE' 'custom/blis2gpr.meta'
data_file 'HANDLING_FILE' 'custom/buffalo4h.meta'
data_file 'HANDLING_FILE' 'custom/callista.meta'
data_file 'HANDLING_FILE' 'custom/caracaran.meta'
data_file 'HANDLING_FILE' 'custom/coqvice.meta'
data_file 'HANDLING_FILE' 'custom/cycloneex0.meta'
data_file 'HANDLING_FILE' 'custom/cypherct.meta'
data_file 'HANDLING_FILE' 'custom/dubsta22.meta'
data_file 'HANDLING_FILE' 'custom/elegyrh5.meta'
data_file 'HANDLING_FILE' 'custom/elegyx.meta'
data_file 'HANDLING_FILE' 'custom/espexecutive.meta'
data_file 'HANDLING_FILE' 'custom/estancia.meta'
data_file 'HANDLING_FILE' 'custom/fx7r.meta'
data_file 'HANDLING_FILE' 'custom/gauntletctx.meta'
data_file 'HANDLING_FILE' 'custom/gauntlets.meta'
data_file 'HANDLING_FILE' 'custom/gresleyh.meta'
data_file 'HANDLING_FILE' 'custom/gstarg2.meta'
data_file 'HANDLING_FILE' 'custom/gstbisxl3.meta'
data_file 'HANDLING_FILE' 'custom/gstbufst1.meta'
data_file 'HANDLING_FILE' 'custom/gstgauntc2.meta'
data_file 'HANDLING_FILE' 'custom/gstsadlt1.meta'
data_file 'HANDLING_FILE' 'custom/gstsg71.meta'
data_file 'HANDLING_FILE' 'custom/gstvectre1.meta'
data_file 'HANDLING_FILE' 'custom/hycrh7.meta'
data_file 'HANDLING_FILE' 'custom/jdvigeror.meta'
data_file 'HANDLING_FILE' 'custom/mesaxl.meta'
data_file 'HANDLING_FILE' 'custom/mf1.meta'
data_file 'HANDLING_FILE' 'custom/nerops.meta'
data_file 'HANDLING_FILE' 'custom/nsandstorm.meta'
data_file 'HANDLING_FILE' 'custom/nscout.meta'
data_file 'HANDLING_FILE' 'custom/osirisr.meta'
data_file 'HANDLING_FILE' 'custom/pbbgtsj.meta'
data_file 'HANDLING_FILE' 'custom/pentro.meta'
data_file 'HANDLING_FILE' 'custom/remustwo.meta'
data_file 'HANDLING_FILE' 'custom/revolutionw.meta'
data_file 'HANDLING_FILE' 'custom/schlagenstr.meta'
data_file 'HANDLING_FILE' 'custom/sheavas.meta'
data_file 'HANDLING_FILE' 'custom/sultanrsv8.meta'
data_file 'HANDLING_FILE' 'custom/superd3.meta'
data_file 'HANDLING_FILE' 'custom/supergts.meta'
data_file 'HANDLING_FILE' 'custom/tempestaes.meta'
data_file 'HANDLING_FILE' 'custom/tempestafr.meta'
data_file 'HANDLING_FILE' 'custom/turismo2lm.meta'
data_file 'HANDLING_FILE' 'custom/vincent2.meta'
data_file 'HANDLING_FILE' 'custom/vulture.meta'

-- Custom (Gabz)
data_file 'HANDLING_FILE' 'custom/gb_811s2.meta'
data_file 'HANDLING_FILE' 'custom/gb_admiral.meta'
data_file 'HANDLING_FILE' 'custom/gb_admiralpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_archerpro2.meta'
data_file 'HANDLING_FILE' 'custom/gb_argento2f.meta'
data_file 'HANDLING_FILE' 'custom/gb_argento7fpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_argento7fs.meta'
data_file 'HANDLING_FILE' 'custom/gb_argento7ftaxi.meta'
data_file 'HANDLING_FILE' 'custom/gb_banshees.meta'
data_file 'HANDLING_FILE' 'custom/gb_bansheespol.meta'
data_file 'HANDLING_FILE' 'custom/gb_bisonhf.meta'
data_file 'HANDLING_FILE' 'custom/gb_bisonhfpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_bisonstx.meta'
data_file 'HANDLING_FILE' 'custom/gb_bisonstxems.meta'
data_file 'HANDLING_FILE' 'custom/gb_bisonstxpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_boxboy.meta'
data_file 'HANDLING_FILE' 'custom/gb_boxboyft.meta'
data_file 'HANDLING_FILE' 'custom/gb_briosof.meta'
data_file 'HANDLING_FILE' 'custom/gb_cheetahs.meta'
data_file 'HANDLING_FILE' 'custom/gb_clubxr.meta'
data_file 'HANDLING_FILE' 'custom/gb_clubxrpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_cometclpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_comets1t.meta'
data_file 'HANDLING_FILE' 'custom/gb_comets1tf.meta'
data_file 'HANDLING_FILE' 'custom/gb_comets2rc.meta'
data_file 'HANDLING_FILE' 'custom/gb_comets2rpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_cyphergts.meta'
data_file 'HANDLING_FILE' 'custom/gb_delivere.meta'
data_file 'HANDLING_FILE' 'custom/gb_dominatorgsx.meta'
data_file 'HANDLING_FILE' 'custom/gb_dominatorgsxpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_echelon.meta'
data_file 'HANDLING_FILE' 'custom/gb_echelonpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_echelons.meta'
data_file 'HANDLING_FILE' 'custom/gb_elegyrh2.meta'
data_file 'HANDLING_FILE' 'custom/gb_emerussb1.meta'
data_file 'HANDLING_FILE' 'custom/gb_eon.meta'
data_file 'HANDLING_FILE' 'custom/gb_eonpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_eontaxi.meta'
data_file 'HANDLING_FILE' 'custom/gb_erotiq.meta'
data_file 'HANDLING_FILE' 'custom/gb_esperta.meta'
data_file 'HANDLING_FILE' 'custom/gb_espertaems.meta'
data_file 'HANDLING_FILE' 'custom/gb_espertapol.meta'
data_file 'HANDLING_FILE' 'custom/gb_esurfer.meta'
data_file 'HANDLING_FILE' 'custom/gb_gresleypol.meta'
data_file 'HANDLING_FILE' 'custom/gb_hades.meta'
data_file 'HANDLING_FILE' 'custom/gb_harmann.meta'
data_file 'HANDLING_FILE' 'custom/gb_hedra.meta'
data_file 'HANDLING_FILE' 'custom/gb_hedrakombi.meta'
data_file 'HANDLING_FILE' 'custom/gb_hedrapol.meta'
data_file 'HANDLING_FILE' 'custom/gb_hurricane.meta'
data_file 'HANDLING_FILE' 'custom/gb_impaler.meta'
data_file 'HANDLING_FILE' 'custom/gb_impalerdlx.meta'
data_file 'HANDLING_FILE' 'custom/gb_impalerpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_irisz.meta'
data_file 'HANDLING_FILE' 'custom/gb_issimetro.meta'
data_file 'HANDLING_FILE' 'custom/gb_komodagt.meta'
data_file 'HANDLING_FILE' 'custom/gb_lod4.meta'
data_file 'HANDLING_FILE' 'custom/gb_milano.meta'
data_file 'HANDLING_FILE' 'custom/gb_mochi.meta'
data_file 'HANDLING_FILE' 'custom/gb_mogulrs.meta'
data_file 'HANDLING_FILE' 'custom/gb_mojave.meta'
data_file 'HANDLING_FILE' 'custom/gb_mojavepol.meta'
data_file 'HANDLING_FILE' 'custom/gb_mugello.meta'
data_file 'HANDLING_FILE' 'custom/gb_neonct.meta'
data_file 'HANDLING_FILE' 'custom/gb_nexusrr.meta'
data_file 'HANDLING_FILE' 'custom/gb_prospero.meta'
data_file 'HANDLING_FILE' 'custom/gb_prosperopol.meta'
data_file 'HANDLING_FILE' 'custom/gb_raidillon.meta'
data_file 'HANDLING_FILE' 'custom/gb_romulus.meta'
data_file 'HANDLING_FILE' 'custom/gb_ronin.meta'
data_file 'HANDLING_FILE' 'custom/gb_rumina.meta'
data_file 'HANDLING_FILE' 'custom/gb_sapphire.meta'
data_file 'HANDLING_FILE' 'custom/gb_schlagenr.meta'
data_file 'HANDLING_FILE' 'custom/gb_schlagensp.meta'
data_file 'HANDLING_FILE' 'custom/gb_schwartzers.meta'
data_file 'HANDLING_FILE' 'custom/gb_scoutgsx.meta'
data_file 'HANDLING_FILE' 'custom/gb_scoutgsxpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_sentinelgts.meta'
data_file 'HANDLING_FILE' 'custom/gb_sentinelgtspol.meta'
data_file 'HANDLING_FILE' 'custom/gb_sidewinder.meta'
data_file 'HANDLING_FILE' 'custom/gb_solacepol.meta'
data_file 'HANDLING_FILE' 'custom/gb_solacev.meta'
data_file 'HANDLING_FILE' 'custom/gb_stanierle.meta'
data_file 'HANDLING_FILE' 'custom/gb_stanierlepol.meta'
data_file 'HANDLING_FILE' 'custom/gb_stanierletaxi.meta'
data_file 'HANDLING_FILE' 'custom/gb_starlight.meta'
data_file 'HANDLING_FILE' 'custom/gb_starlightpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_starlighttaxi.meta'
data_file 'HANDLING_FILE' 'custom/gb_steed.meta'
data_file 'HANDLING_FILE' 'custom/gb_steedems.meta'
data_file 'HANDLING_FILE' 'custom/gb_steedpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_sultanrsxpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_tahomagt.meta'
data_file 'HANDLING_FILE' 'custom/gb_tahomagtpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_tempestafs.meta'
data_file 'HANDLING_FILE' 'custom/gb_tenfr.meta'
data_file 'HANDLING_FILE' 'custom/gb_terrorizer.meta'
data_file 'HANDLING_FILE' 'custom/gb_terrorizerpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_tr3spol.meta'
data_file 'HANDLING_FILE' 'custom/gb_turismogt.meta'
data_file 'HANDLING_FILE' 'custom/gb_turismogtpol.meta'
data_file 'HANDLING_FILE' 'custom/gb_turismogts.meta'
data_file 'HANDLING_FILE' 'custom/gb_vigerorat.meta'
data_file 'HANDLING_FILE' 'custom/gb_vivant.meta'
data_file 'HANDLING_FILE' 'custom/gb_vivantgrb.meta'
data_file 'HANDLING_FILE' 'custom/gb_voyager.meta'
data_file 'HANDLING_FILE' 'custom/gb_voyagerfire.meta'
data_file 'HANDLING_FILE' 'custom/gb_zeitgeist.meta'
