-- Gabz vehicles - add to vehicle_catalog as custom tier
USE `blacklist_racing`;

INSERT INTO `vehicle_catalog` (`model`, `label`, `tier`, `class`) VALUES
('gb_811s2', '811S2', 'custom', 'sports'),
('gb_admiral', 'Admiral', 'custom', 'sports'),
('gb_archerpro2', 'Archerpro2', 'custom', 'sports'),
('gb_argento2f', 'Argento2f', 'custom', 'sports'),
('gb_argento7fs', 'Argento7fs', 'custom', 'sports'),
('gb_argento7ftaxi', 'Argento7ftaxi', 'custom', 'service'),
('gb_argento7f', 'Argento7f', 'custom', 'sports'),
('gb_banshees', 'Banshees', 'custom', 'sports'),
('gb_bisonhf', 'Bisonhf', 'custom', 'sports'),
('gb_bisonstx', 'Bisonstx', 'custom', 'sports'),
('gb_boxboyft', 'Boxboyft', 'custom', 'sports'),
('gb_boxboy', 'Boxboy', 'custom', 'sports'),
('gb_briosof', 'Briosof', 'custom', 'sports'),
('gb_cheetahs', 'Grotti Cheetah S', 'custom', 'sports'),
('gb_clubxr', 'Clubxr', 'custom', 'sports'),
('gb_cometclf', 'Comet Classic Florio', 'custom', 'sports'),
('gb_cometcl', 'Comet Classic', 'custom', 'sports'),
('gb_comets1tf', 'Comet S1 Turbo Florio', 'custom', 'sports'),
('gb_comets1t', 'Comet S1 Turbo', 'custom', 'sports'),
('gb_comets2rc', 'Comets2rc', 'custom', 'sports'),
('gb_comets2r', 'Comets2r', 'custom', 'sports'),
('gb_cyphergts', 'Cypher GTS', 'custom', 'sports'),
('gb_delivere', 'Delivere', 'custom', 'sports'),
('gb_dominatorgsx', 'Dominatorgsx', 'custom', 'sports'),
('gb_echelons', 'Echelons', 'custom', 'sports'),
('gb_echelon', 'Echelon', 'custom', 'sports'),
('gb_elegyrh2', 'Elegyrh2', 'custom', 'sports'),
('gb_emerussb1', 'Emerussb1', 'custom', 'sports'),
('gb_eontaxi', 'Eontaxi', 'custom', 'service'),
('gb_eon', 'Eon', 'custom', 'sports'),
('gb_erotiq', 'Erotiq', 'custom', 'sports'),
('gb_gresleystx', 'Gresleystx', 'custom', 'sports'),
('gb_esperta', 'Esperta', 'custom', 'sports'),
('gb_esurfer', 'e-Surfer', 'custom', 'sports'),
('gb_hades', 'Hades', 'custom', 'sports'),
('gb_harmann', 'Harmann', 'custom', 'sports'),
('gb_hedrakombi', 'Hedrakombi', 'custom', 'sports'),
('gb_hedra', 'Hedra', 'custom', 'sports'),
('gb_hurricane', 'Hurricane', 'custom', 'sports'),
('gb_impalerdlx', 'Impalerdlx', 'custom', 'sports'),
('gb_impaler', 'Impaler', 'custom', 'sports'),
('gb_irisz', 'Irisz', 'custom', 'sports'),
('gb_issimetro', 'Issimetro', 'custom', 'sports'),
('gb_komodagt', 'Komodagt', 'custom', 'sports'),
('gb_lod4', 'Lod4', 'custom', 'sports'),
('gb_milano', 'Milano', 'custom', 'sports'),
('gb_mochi', 'Mochi', 'custom', 'sports'),
('gb_mogulrs', 'Mogulrs', 'custom', 'sports'),
('gb_mojave', 'Mojave', 'custom', 'sports'),
('gb_mugello', 'Mugello', 'custom', 'sports'),
('gb_neonct', 'Neonct', 'custom', 'sports'),
('gb_nexusrr', 'Nexusrr', 'custom', 'sports'),
('gb_prospero', 'Prospero', 'custom', 'sports'),
('gb_raidillon', 'Raidillon', 'custom', 'sports'),
('gb_retinueloz', 'Retinueloz', 'custom', 'sports'),
('gb_romulus', 'Romulus', 'custom', 'sports'),
('gb_ronin', 'Ronin', 'custom', 'sports'),
('gb_rumina', 'Rumina', 'custom', 'sports'),
('gb_sapphire', 'Sapphire', 'custom', 'sports'),
('gb_schlagenr', 'Schlagenr', 'custom', 'sports'),
('gb_schlagensp', 'Schlagensp', 'custom', 'sports'),
('gb_schrauber', 'Schrauber', 'custom', 'sports'),
('gb_schwartzers', 'Schwartzers', 'custom', 'sports'),
('gb_scoutgsx', 'Scoutgsx', 'custom', 'sports'),
('gb_sentinelgts', 'Sentinelgts', 'custom', 'sports'),
('gb_sidewinder', 'Sidewinder', 'custom', 'sports'),
('gb_solacev', 'Solacev', 'custom', 'sports'),
('gb_solace', 'Solace', 'custom', 'sports'),
('gb_stanierletaxi', 'Stanierletaxi', 'custom', 'service'),
('gb_stanierle', 'Stanierle', 'custom', 'sports'),
('gb_starlighttaxi', 'Starlighttaxi', 'custom', 'service'),
('gb_starlight', 'Starlight', 'custom', 'sports'),
('gb_steed', 'Steed', 'custom', 'sports'),
('gb_sultanrsx', 'Sultanrsx', 'custom', 'sports'),
('gb_tahomagt', 'Tahomagt', 'custom', 'sports'),
('gb_tempestafs', 'Tempestafs', 'custom', 'sports'),
('gb_tenfr', 'Tenfr', 'custom', 'sports'),
('gb_terrorizer', 'Terrorizer', 'custom', 'sports'),
('gb_tr3s', 'Tr3s', 'custom', 'sports'),
('gb_turismogts', 'Turismogts', 'custom', 'sports'),
('gb_turismogt', 'Turismogt', 'custom', 'sports'),
('gb_vigerorat', 'Vigerorat', 'custom', 'sports'),
('gb_vivantgrb', 'Vivantgrb', 'custom', 'sports'),
('gb_vivant', 'Vivant', 'custom', 'sports'),
('gb_voyager', 'Voyager', 'custom', 'sports'),
('gb_zeitgeist', 'Zeitgeist', 'custom', 'sports'),
('gb_admiralpol', 'Admiralpol', 'custom', 'police'),
('gb_argento7fpol', 'Argento7fpol', 'custom', 'police'),
('gb_bansheespol', 'Bansheespol', 'custom', 'police'),
('gb_bisonhfpol', 'Bisonhfpol', 'custom', 'police'),
('gb_bisonstxems', 'Bisonstxems', 'custom', 'emergency'),
('gb_bisonstxpol', 'Bisonstxpol', 'custom', 'police'),
('gb_clubxrpol', 'Clubxrpol', 'custom', 'police'),
('gb_cometclpol', 'Comet Classic Police', 'custom', 'police'),
('gb_comets2rpol', 'Comets2rpol', 'custom', 'police'),
('gb_dominatorgsxpol', 'Dominatorgsxpol', 'custom', 'police'),
('gb_echelonpol', 'Echelonpol', 'custom', 'police'),
('gb_eonpol', 'Eonpol', 'custom', 'police'),
('gb_espertaems', 'Espertaems', 'custom', 'emergency'),
('gb_espertapol', 'Espertapol', 'custom', 'police'),
('gb_gresleypol', 'Gresleypol', 'custom', 'police'),
('gb_hedrapol', 'Hedrapol', 'custom', 'police'),
('gb_impalerpol', 'Impalerpol', 'custom', 'police'),
('gb_mojavepol', 'Mojavepol', 'custom', 'police'),
('gb_pol_main', 'Buffalo ST PI', 'custom', 'sports'),
('gb_prosperopol', 'Prosperopol', 'custom', 'police'),
('gb_scoutgsxpol', 'Scoutgsxpol', 'custom', 'police'),
('gb_sentinelgtspol', 'Sentinelgtspol', 'custom', 'police'),
('gb_solacepol', 'Solacepol', 'custom', 'police'),
('gb_stanierlepol', 'Stanierlepol', 'custom', 'police'),
('gb_starlightpol', 'Starlightpol', 'custom', 'police'),
('gb_steedems', 'Steedems', 'custom', 'emergency'),
('gb_steedpol', 'Steedpol', 'custom', 'police'),
('gb_sultanrsxpol', 'Sultanrsxpol', 'custom', 'police'),
('gb_tahomagtpol', 'Los Santos Police Department', 'custom', 'police'),
('gb_terrorizerpol', 'Terrorizerpol', 'custom', 'police'),
('gb_turismogtpol', 'Turismogtpol', 'custom', 'police'),
('gb_tr3spol', 'Tr3spol', 'custom', 'police'),
('gb_voyagerfire', 'Voyagerfire', 'custom', 'emergency')
ON DUPLICATE KEY UPDATE `label` = VALUES(`label`), `tier` = VALUES(`tier`);
