-- Gabz vehicles - add to vehicle_catalog (correct model names from vehicles.meta)
USE `blacklist_racing`;

INSERT INTO `vehicle_catalog` (`model`, `label`, `tier`, `class`) VALUES
('gb811s2', '811 S2', 'custom', 'sports'),
('gbadmiral', 'Admiral', 'custom', 'sports'),
('gbarcherpro2', 'gbarcherpro2', 'custom', 'sports'),
('gbargento2f', 'gbargento2f', 'custom', 'sports'),
('gbargento2f', 'gbargento2f', 'custom', 'sports'),
('gbargento7fs', 'gbargento7fs', 'custom', 'sports'),
('gbtaxiargento7f', 'gbtaxiargento7f', 'custom', 'service'),
('gbargento7f', 'gbargento7f', 'platinum', 'sports'),
('gbbanshees', 'gbbanshees', 'custom', 'sports'),
('gbbisonhf', 'Bison HF', 'custom', 'sports'),
('gbbisonstx', 'gbbisonstx', 'custom', 'sports'),
('gbboxboyft', 'Boxboy Food Truck', 'custom', 'sports'),
('gbboxboy', 'Boxboy', 'custom', 'sports'),
('gbbriosof', 'gbbriosof', 'custom', 'sports'),
('gbcheetahs', 'Grotti Cheetah S', 'custom', 'sports'),
('gbclubxr', 'Club XR', 'custom', 'sports'),
('gbcometclf', 'gbcometclf', 'silver', 'sports'),
('gbcometcl', 'gbcometcl', 'bronze', 'sports'),
('gbcomets1tf', 'gbcomets1tf', 'custom', 'sports'),
('gbcomets1t', 'gbcomets1t', 'custom', 'sports'),
('gbcomets2rc', 'Comet S2RC', 'custom', 'sports'),
('gbcomets2r', 'Comet S2R', 'blacklist', 'sports'),
('gbcyphergts', 'Cypher GTS', 'custom', 'sports'),
('gbdelivere', 'gbdelivere', 'custom', 'sports'),
('gbdominatorgsx', 'gbdominatorgsx', 'custom', 'sports'),
('gbechelons', 'Echelon Sportback', 'custom', 'sports'),
('gbechelon', 'Echelon', 'custom', 'sports'),
('gbelegyrh2', 'gbelegyrh2', 'custom', 'sports'),
('gbemerussb1', 'gbemerussb1', 'custom', 'sports'),
('gbtaxieon', 'Taxi Eon', 'custom', 'service'),
('gbeon', 'Eon', 'custom', 'sports'),
('gberotiq', 'E-Rotiq', 'custom', 'sports'),
('gbgresleystx', 'gbgresleystx', 'gold', 'sports'),
('gbesperta', 'Rumpo Esperta', 'custom', 'sports'),
('gbesurfer', 'e-Surfer', 'custom', 'sports'),
('gbhades', 'Hades', 'custom', 'sports'),
('gbharmann', 'Harmann', 'custom', 'sports'),
('gbhedrakombi', 'gbhedrakombi', 'custom', 'sports'),
('gbhedra', 'Hedra', 'custom', 'sports'),
('gbhurricane', 'gbhurricane', 'custom', 'sports'),
('gbimpalerdlx', 'gbimpalerdlx', 'custom', 'sports'),
('gbimpaler', 'Impaler LE', 'custom', 'sports'),
('gbirisz', 'Iris Z', 'custom', 'sports'),
('gbissimetro', 'gbissimetro', 'custom', 'sports'),
('gbkomodagt', 'Komoda GT', 'custom', 'sports'),
('gblod4', 'LOD-4', 'custom', 'sports'),
('gbmilano', 'Milano GTS', 'custom', 'sports'),
('gbmochi', 'Mochi', 'custom', 'sports'),
('gbmogulrs', 'Mogul RS', 'custom', 'sports'),
('gbmojave', 'Mojave', 'custom', 'sports'),
('gbmugello', 'gbmugello', 'custom', 'sports'),
('gbneonct', 'Neon Cross Turismo', 'custom', 'sports'),
('gbnexusrr', 'gbnexusrr', 'custom', 'sports'),
('gbprospero', 'Prospero', 'custom', 'sports'),
('gbraidillon', 'gbraidillon', 'custom', 'sports'),
('gbretinueloz', 'gbretinueloz', 'silver', 'sports'),
('gbromulus', 'Romulus', 'custom', 'sports'),
('gbronin', 'Ronin', 'custom', 'sports'),
('gbrumina', 'Rumina', 'custom', 'sports'),
('gbsapphire', 'Sapphire', 'custom', 'sports'),
('gbschlagenr', 'Schlagen Roadster', 'custom', 'sports'),
('gbschlagensp', 'gbschlagensp', 'custom', 'sports'),
('gbschrauber', 'gbschrauber', 'silver', 'sports'),
('gbschwartzers', 'gbschwartzers', 'custom', 'sports'),
('gbscoutgsx', 'Scout GSX', 'custom', 'sports'),
('gbsentinelgts', 'gbsentinelgts', 'custom', 'sports'),
('gbsidewinder', 'gbsidewinder', 'custom', 'sports'),
('gbsolacev', 'gbsolacev', 'custom', 'sports'),
('gbsolace', 'gbsolace', 'platinum', 'sports'),
('gbtaxistanierle', 'gbtaxistanierle', 'custom', 'service'),
('gbstanierle', 'Stanier LE', 'custom', 'sports'),
('gbtaxistarlight', 'gbtaxistarlight', 'custom', 'service'),
('gbstarlight', 'gbstarlight', 'custom', 'sports'),
('gbsteedvan', 'gbsteedvan', 'custom', 'sports'),
('gbsteedcrew', 'gbsteedcrew', 'custom', 'sports'),
('gbsultanrsx', 'gbsultanrsx', 'platinum', 'sports'),
('gbtahomagt', 'gbtahomagt', 'custom', 'sports'),
('gbtempestafs', 'gbtempestafs', 'custom', 'sports'),
('gbtenfr', 'gbtenfr', 'custom', 'sports'),
('gbterrorizer', 'gbterrorizer', 'custom', 'sports'),
('gbtr3s', 'gbtr3s', 'diamond', 'sports'),
('gbturismogts', 'gbturismogts', 'custom', 'sports'),
('gbturismogt', 'gbturismogt', 'custom', 'sports'),
('gbvigerorat', 'gbvigerorat', 'custom', 'sports'),
('gbvivantgrb', 'gbvivantgrb', 'custom', 'sports'),
('gbvivant', 'Vivant', 'custom', 'sports'),
('gbvoyager', 'Voyager 6x4-T', 'custom', 'sports'),
('gbvoyager2', 'Voyager 4x2-T', 'custom', 'sports'),
('gbvoyagerb', 'Voyager 6x4-B', 'custom', 'sports'),
('gbvoyagerb2', 'Voyager 4x2-B', 'custom', 'sports'),
('gbvoyagerg', 'Voyager Trash Truck', 'custom', 'sports'),
('gbvoyagerh', 'Voyager 6x2-H', 'custom', 'sports'),
('gbzeitgeist', 'Zeitgeist', 'custom', 'sports'),
('gbpoladmiral', 'gbpoladmiral', 'custom', 'police'),
('gbpolargento7f', 'gbpolargento7f', 'custom', 'police'),
('gbpolbanshees', 'gbpolbanshees', 'custom', 'police'),
('gbpolbisonhf', 'gbpolbisonhf', 'custom', 'police'),
('gbemsbisonstx', 'gbemsbisonstx', 'custom', 'emergency'),
('gbpolbisonstx', 'gbpolbisonstx', 'custom', 'police'),
('gbpolclubxr', 'Club XR Police', 'custom', 'police'),
('gbpolcometcl', 'gbpolcometcl', 'custom', 'police'),
('gbpolcomets2r', 'gbpolcomets2r', 'custom', 'police'),
('gbpoldomgsx', 'Police Dominator GSX', 'custom', 'police'),
('gbpolechelon', 'gbpolechelon', 'custom', 'police'),
('gbpoleon', 'Eon Police', 'custom', 'police'),
('gbemsesperta', 'gbemsesperta', 'custom', 'emergency'),
('gbpolesperta', 'gbpolesperta', 'custom', 'police'),
('gbpolgresley', 'gbpolgresley', 'custom', 'police'),
('gbpolhedra', 'Hedra Kombi Police', 'custom', 'police'),
('gbpolimpaler', 'gbpolimpaler', 'custom', 'police'),
('gbpolmojave', 'Police Mojave', 'custom', 'police'),
('gbpolprospero', 'gbpolprospero', 'custom', 'police'),
('gbpolscoutgsx', 'gbpolscoutgsx', 'custom', 'police'),
('gbpolsentinelgts', 'gbpolsentinelgts', 'custom', 'police'),
('gbpolsolace', 'gbpolsolace', 'custom', 'police'),
('gbpolstanier', 'gbpolstanier', 'custom', 'police'),
('gbpolstarlight', 'gbpolstarlight', 'custom', 'police'),
('gbemssteed', 'gbemssteed', 'custom', 'emergency'),
('gbpolsteedvan', 'gbpolsteedvan', 'custom', 'police'),
('gbpolsultanrsx', 'gbpolsultanrsx', 'custom', 'police'),
('gbpoltahomagt', 'gbpoltahomagt', 'custom', 'police'),
('gbpolterrorizer', 'gbpolterrorizer', 'custom', 'police'),
('gbpolturismogt', 'gbpolturismogt', 'custom', 'police'),
('gbpoltr3s', 'gbpoltr3s', 'custom', 'police'),
('gbfirevoyager', 'gbfirevoyager', 'custom', 'emergency')
ON DUPLICATE KEY UPDATE `label` = VALUES(`label`), `tier` = VALUES(`tier`);